azavea/nasa-hyperspectral

.gitignore
deployment/terraform/firewall.tf
docker-compose.yml
src/pipeline/activator/aviris-l2/README.md
src/pipeline/activator/aviris-l2/main.py

1. This PR fixes AVIRIS catalog names changed in terms of #89 
2. Exposes catalog as a parameter that can be overrided.
3. Exposes FTP ports for the Batch.
4. Adjusts env variables names

Adjust activator params

---

docker-compose.yml
src/catalogs/aviris/aviris_df/__init__.py
src/catalogs/aviris/main.py
src/pipeline/activator/aviris-l2/main.py
src/pipeline/activator/aviris-l2/progress.py

This PR addresses result COGs rotation to make they easier in use and fixes all Py scripts logging level.
Closes #94
Closes #96

Activator AVIRIS rotation fix

---

src/pipeline/activator/cog-clip/build.sbt
src/pipeline/activator/cog-clip/src/main/resources/logback.xml
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/Main.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/commands/CogClip.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/util/StacClientLoggingMid.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/util/package.scala

This PR adds stac4s client logging

Add stac4s client logging

---

src/pipeline/activator/cog-clip/build.sbt

This PR updates Scala deps and Scala version

Upd Scala and deps

---

src/pipeline/activator/cog-clip/build.sbt
src/pipeline/activator/cog-clip/project/build.properties
src/pipeline/activator/cog-clip/project/plugins.sbt
src/pipeline/activator/cog-clip/sbt
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/commands/CogClip.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/commands/DefaultCollection.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/util/logging/StacClientLoggingMid.scala
src/pipeline/activator/cog-clip/src/main/scala/com/azavea/nasa/hsi/util/logging/StreamingStacClientLoggingMid.scala

This PR bumps all deps up, but it depends on https://github.com/azavea/stac4s/pull/346 which was already tested via https://gist.github.com/pomadchin/86e61dc151fbf2be9fa9f824473071b7
Connects #130

Update SBT and deps

---

.github/workflows/ci-stac.yml
.github/workflows/ci.yml
.gitignore
docs/stac-spec/hsi/README.md
docs/stac-spec/hsi/examples/item.json
docs/stac-spec/hsi/json-schema/schema.json
docs/stac-spec/hsi/package.json
src/pipeline/activator/aviris-l2/config.py
src/pipeline/activator/aviris-l2/main.py
src/pipeline/activator/aviris-l2/progress.py
src/pipeline/activator/aviris-l2/s3uri.py
src/pipeline/activator/cog-clip/build.sbt
src/pipeline/activator/prisma/config.py
src/pipeline/activator/prisma/main.py
src/pipeline/activator/prisma/progress.py
src/pipeline/activator/prisma/s3uri.py

This PR adds a scaffold and the current descriptions of the HSI extension.
Closes https://github.com/azavea/nasa-hyperspectral/issues/161
Closes https://github.com/azavea/nasa-hyperspectral/issues/153

Add HSI STAC Spec description and tests

---

deployment/argo-workflows/eks/README.md
deployment/argo-workflows/eks/workflow-aviris-l2-scene-id.yaml
deployment/terraform/eks-iam.tf
scripts/cipublish

This PR adds EKS Workers an autoscaling policy, modifies CI and adjusts worfklows yaml files.

EKS Workflows Improvements

---

deployment/argo-workflows/eks/workflow-aviris-l1-scene-id-gtiff.yaml
scripts/test-argo
src/pipeline/activator/aviris-l1/config.py
src/pipeline/activator/aviris-l1/main.py
src/pipeline/activator/aviris-l2/config.py
src/pipeline/activator/aviris-l2/main.py
src/pipeline/activator/prisma/config.py
src/pipeline/activator/prisma/main.py

Add no overviews mode into preprocessor scripts

---

deployment/argo-workflows/eks/INSTALL.md
deployment/argo-workflows/eks/README.md
deployment/argo-workflows/eks/manifests/install-argo.yaml

Update ArgoWorkflows up to v3.1.3

---

deployment/argo-workflows/eks/workflow-aviris-l1-scene-id-gtiff.yaml
src/pipeline/activator/aviris-l1/progress.py
src/pipeline/activator/aviris-l2/progress.py
src/pipeline/activator/prisma/progress.py

Rollback progressbar and update workflow yaml

---

deployment/argo-workflows/eks/INSTALL.md
deployment/argo-workflows/eks/workflow-prisma-path.yaml
src/pipeline/activator/aviris-l1/main.py
src/pipeline/activator/aviris-l2/main.py
src/pipeline/activator/prisma/main.py

This PR adds Processors tiling (in case a non COG GDAL driver was used) and add a PRISMA workflow yaml.
Connects #166

Add Processors tiling and add PRISMA workflow

---

src/pipeline/activator/prisma/main.py

Fix PRISMA Processor output paths

---

deployment/argo-workflows/eks/INSTALL.md
deployment/argo-workflows/eks/helm/autoscaler-chart-values.yaml

Add K8S Autoscaler Helm chart

---

src/pipeline/activator/aviris-l1/main.py
src/pipeline/activator/aviris-l2/main.py
src/pipeline/activator/prisma/main.py

Fix Processors tiling

---

src/hyperspectral/notebooks/Algal Bloom Exploration.ipynb
src/hyperspectral/notebooks/Deepwater Horizon Exploration.ipynb
src/hyperspectral/notebooks/Emperical Oil Spectra.ipynb

A notebook to perform band selection on empirical oil spectra.
Closes #157 
224 bands:
48 bands:
(Contrast levels are not necessarily meaningful.)
Bands sorted from worst to best:
```python
array([[154],
[176],
[ 14],
[  7],
[156],
[157],
[179],
[177],
[ 28],
[147],
[ 17],
[180],
[152],
[  1],
[136],
[106],
[145],
[ 36],
[105],
[108],
[198],
[146],
[ 16],
[151],
[112],
[  8],
[114],
[104],
[113],
[ 69],
[109],
[155],
[ 10],
[107],
[148],
[103],
[ 66],
[193],
[195],
[178],
[153],
[ 18],
[137],
[115],
[172],
[197],
[159],
[149],
[181],
[ 19],
[158],
[194],
[ 39],
[110],
[139],
[ 70],
[150],
[188],
[116],
[  5],
[138],
[  0],
[185],
[  3],
[192],
[171],
[196],
[  4],
[  6],
[ 68],
[ 15],
[135],
[182],
[  2],
[118],
[200],
[199],
[111],
[134],
[ 62],
[189],
[175],
[117],
[119],
[ 43],
[ 20], …
```

Oil Band Selection

---

deployment/argo-workflows/eks/INSTALL.md
deployment/argo-workflows/eks/manifests/install-argo.yaml
deployment/argo-workflows/eks/workflow-aviris-l1-scene-id.yaml
deployment/argo-workflows/eks/workflow-two.yaml

This PR updates ARGO up to the latest version and updates workflows manifests to lower GDAL memory usage

Update Argo manifests

---

deployment/argo-workflows/eks/INSTALL.md
deployment/terraform/eks.tf

Split EKS Workers into two groups, one of which is supports autoscaling.

EKS Workers Autoscaling

---

src/utils/.gitignore
src/utils/planet-query.py

This PR contains a small change to the Planet API query script to allow it to function in the presence of non-existent IDs.

Planet Query Script: Minor Update

---

research/src/algae-model/.gitignore
research/src/algae-model/rastervision/cloud-catalogs.json
research/src/algae-model/rastervision/pipeline.py
research/src/algae-model/rastervision/tree-catalogs.json
research/src/algae-model/src/cheaplab_view.py
research/src/algae-model/src/cloud.py
research/src/algae-model/src/datasets.py
research/src/algae-model/src/train_seg.py

This PR brings in updated algae and tree machine learning code.

Update Algae and Tree Models

---

research/src/algae-model/.gitignore
research/src/algae-model/scripts/one-time-use/dissolve.py
research/src/algae-model/scripts/one-time-use/get-red.py
research/src/algae-model/src/cheaplab_view.py
research/src/algae-model/src/cloud.py
research/src/algae-model/src/train_conifer.py
research/src/algae-model/src/train_seg.py
research/src/algae-model/src/tree.py

Update tree health-related machine learning code.

Update Tree Health Code

---

deployment/argo-workflows/azavea-dev/INSTALL.md
deployment/argo-workflows/eks/INSTALL.md
deployment/argo-workflows/eks/manifests/install-argo.yaml
deployment/argo-workflows/local/INSTALL.md

This PR upgrades Argo manifests and docs up to 3.3.5
Closes https://github.com/azavea/nasa-hyperspectral/issues/191

Argo Workflows 3.3.5 upgrade
